Helmet
adobe-rnd/franklin-esr pull request #46
Opened 2022-06-09 16:21 UTC by hannessolo

Fixes #42

2022-06-10 11:36 UTC, icaraps commented on test/test-project/package.json
> +    "babel-plugin-styled-components": "^2.0.7",
Is `babel-plugin-styled-components` and `react-helmet` required for the test project?

2022-06-10 13:52 UTC, mhaack commented on renderer/_default.page.server.jsx
>          <meta name="description" content="demo">
Yes lets move that to Helmet as well, not hard code it.

2022-06-10 14:28 UTC, icaraps commented
Can you pls verify if it works too when doing client-side navigation ?

2022-06-10 19:29 UTC, icaraps commented
Do you also have this warning when running `npm run dev` ?

<img width="689" alt="Screen Shot 2022-06-10 at 9 28 00 PM" src="https://user-images.githubusercontent.com/6012307/173136788-311d170d-d01c-4378-8d7f-631b3861c120.png">

2022-06-10 19:54 UTC, icaraps requested changes

2022-06-10 19:54 UTC, icaraps commented on components/PageLayout.jsx
> +        <link rel="stylesheet" href="/fonts.css" media="print" onLoad="this.media='all'" />
This is a problem when doing client-side navigation, the font will hide and show on every page navigation.
Can we keep the fonts.css and index.css links in the default page server renderer (so not within Helmet) or do you think there's a problem if we do that ?

2022-06-13 06:19 UTC, hannessolo commented
> Do you also have this warning when running `npm run dev` ? I don't have it in worker mode though ...
> 
> <img alt="Screen Shot 2022-06-10 at 9 28 00 PM" width="689" src="https://user-images.githubusercontent.com/6012307/173136788-311d170d-d01c-4378-8d7f-631b3861c120.png">

Yes, looks like an open issue. https://github.com/nfl/react-helmet/issues/548

The fix seems to be to use this fork until they fix it: https://www.npmjs.com/package/react-helmet-async

2022-06-13 08:21 UTC, icaraps commented on package.json
> +    "react-helmet": "^6.1.0",
Can you pls try out https://www.npmjs.com/package/react-helmet-async ?

2022-06-13 08:22 UTC, hannessolo commented on package.json
> +    "react-helmet": "^6.1.0",
Yep, I took a look. But it looks like it will have issues with streaming. https://github.com/staylor/react-helmet-async#streams

2022-06-13 09:22 UTC, icaraps approved these changes

2022-06-13 09:23 UTC, merged